# https://coolors.co/000000-1b1d23-363946-696773-819595-b1b6a6-f8fff4-93c6d6-eca72c
baseurl = "https://www.interdimensionalvortex.com/"
languageCode = "en-us"
languageLang = "en"
title = "The Vortex"

[params]
  description = "The Interdimensional Vortex of Conspiratorial Tastemaking, where good taste comes to die."
  tagline = "Interdimensional Vortex"
  metaimage = "https://www.interdimensionalvortex.com/img/og-image.png"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details:
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS"]

summaryLength = 50

googleAnalyticsID = "G-7FE0NVM2J2"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"